### ISSUE TITLE
Problem to d-dataMappingField

### ISSUE THREAD

**Issue by douglasluis** [spadrapo/drapo#68]
When I create a d-dataMappingField and do not insert data into it, it presents the following error:

Drapo - DrapoEventHandler - ExecuteEvent - Stack: TypeError: data.push is not a function at DrapoStorage.<anonymous> (http://localhost:9900/drapo.js:21116:30) at step (http://localhost:9900/drapo.js:56:23) at Object.next (http://localhost:9900/drapo.js:37:53) at fulfilled (http://localhost:9900/drapo.js:28:58)

**Comment by douglasluis** [comment]
<!DOCTYPE html>
<html>
<head>
    <script src="/drapo.js"></script>
    <title>Error Data Mapping Field</title>
</head>
<body>
    <span>Data Mapping</span>
    <div d-dataKey="objects" d-dataUrlGet="/Data/GetLevels?levels=2&children=2&includeIndex=true"></div>

    <div d-sector="1">
        <div d-dataKey="mappingObject" d-dataType="mapping" d-dataValue="tabs" d-dataMappingField=""></div>
        <span>Sector 1</span>
        <div>
            <div d-for="object in mappingObject">
                <span>Key: </span><span d-model="{{object.Key}}"></span><span> Value: </span><span d-model="{{object.Value}}"></span>
            </div>
        </div>
    </div>
</body>
</html>

**Comment by douglasluis** [comment]
`<!DOCTYPE html>
<html>
<head>
    <script src="/drapo.js"></script>
    <title>Error Data Mapping Field</title>
</head>
<body>
    <span>Data Mapping</span>
    <div d-dataKey="objects" d-dataUrlGet="/Data/GetLevels?levels=2&children=2&includeIndex=true"></div>

    <div d-sector="1">
        <div d-dataKey="mappingObject" d-dataType="mapping" d-dataValue="tabs" d-dataMappingField=""></div>
        <span>Sector 1</span>
        <div>
            <div d-for="object in mappingObject">
                <span>Key: </span><span d-model="{{object.Key}}"></span><span> Value: </span><span d-model="{{object.Value}}"></span>
            </div>
        </div>
    </div>
</body>
</html>`
